services:
  api1: &api
    image: "rinha2023_app:latest"
    network_mode: "host"

    environment:
      SERVER_HOST: localhost
      SERVER_PORT: 6969
      POSTGRES_HOST: localhost
      POSTGRES_USER: bololo
      POSTGRES_PASSWORD: haha
      POSTGRES_DB: shakeit

    entrypoint: /bin/sh -c "/app/main 2>&1 | tee /logs/container1.log"
    volumes:
      - ./logs:/logs

    depends_on:
      db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    <<: *api

    environment:
      SERVER_HOST: localhost
      SERVER_PORT: 4200
      POSTGRES_HOST: localhost
      POSTGRES_USER: bololo
      POSTGRES_PASSWORD: haha
      POSTGRES_DB: shakeit

    entrypoint: /bin/sh -c "/app/main 2>&1 | tee /logs/container2.log"
    volumes:
      - ./logs:/logs

  db:
    image: "postgres:latest"
    # ports:
    #   - 5432:5432
    network_mode: "host"

    environment:
      POSTGRES_USER: bololo
      POSTGRES_PASSWORD: haha
      POSTGRES_DB: shakeit

    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/db.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]

    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'

  nginx:
    image: nginx:alpine
    network_mode: "host"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx

    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
